"""
Simple maps4fs documentation Q&A bot
No greetings, just pure technical answers for community support
"""

from langchain_ollama import OllamaEmbeddings, OllamaLLM
from langchain_chroma import Chroma
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

# ============================================================================
# CONFIGURATION
# ============================================================================

# Hardcoded test question - change this to test different scenarios
QUESTION = "My game hangs on loading when I put the map generated by maps4fs into the mods folder."

# Database and model settings
CHROMA_DB_DIR = "chroma_db"
EMBEDDING_MODEL = "nomic-embed-text"  # For retrieval
LLM_MODEL = "qwen2.5:14b"  # For generating answers
TOP_K_RESULTS = 8  # Number of relevant chunks to retrieve

# Simple, direct prompt - no business fluff
PROMPT_TEMPLATE = """Answer the question using the provided documentation.
Be direct and technical. Include specific commands, file paths, or procedures when available.
Do not add greetings or pleasantries - just provide the answer.

Documentation:
{context}

Question: {question}

Answer:"""


def format_docs(docs):
    """Format retrieved documents for context"""
    return "\n\n".join(doc.page_content for doc in docs)


def answer_question():
    """Answer the hardcoded question using the knowledge base"""

    print(f"Question: {QUESTION}")
    print("\nLoading knowledge base...")

    # Load embeddings and vector store
    embeddings = OllamaEmbeddings(model=EMBEDDING_MODEL)
    vectorstore = Chroma(persist_directory=CHROMA_DB_DIR, embedding_function=embeddings)

    # Initialize LLM
    print("Initializing model...")
    llm = OllamaLLM(
        model=LLM_MODEL, temperature=0.2
    )  # Low temperature for factual answers

    # Setup retriever
    retriever = vectorstore.as_retriever(
        search_type="similarity", search_kwargs={"k": TOP_K_RESULTS}
    )

    # Create simple QA chain
    prompt = ChatPromptTemplate.from_template(PROMPT_TEMPLATE)

    qa_chain = (
        {"context": retriever | format_docs, "question": RunnablePassthrough()}
        | prompt
        | llm
        | StrOutputParser()
    )

    # Generate answer
    print("Generating answer...\n")
    print("=" * 80)

    answer = qa_chain.invoke(QUESTION)
    print(answer)

    print("=" * 80)

    # Show retrieved chunks for debugging
    docs = retriever.invoke(QUESTION)
    print(f"\n[Used {len(docs)} chunks from documentation]")
    print("Retrieved sources:")
    for i, doc in enumerate(docs, 1):
        source = doc.metadata.get("source", "Unknown")
        print(f"  {i}. {source}")


if __name__ == "__main__":
    answer_question()
